package engine

import (
	"context"
	"fmt"
	"strings"

	"github.com/shivamstaq/github-symphony/internal/codehost"
	"github.com/shivamstaq/github-symphony/internal/domain"
)

// HandoffInput contains the data needed to evaluate handoff.
type HandoffInput struct {
	HasPR                bool
	CurrentProjectStatus string
	HandoffProjectStatus string // configured target status for handoff
	RequiredChecks       []string
	PassedChecks         []string
}

// HandoffResult is the outcome of handoff evaluation.
type HandoffResult struct {
	IsHandoff bool
	Reason    string
}

// EvaluateHandoff determines whether a work item has met the handoff criteria.
//
// Rules:
//  1. handoff_project_status must be configured (non-empty)
//  2. A PR must exist
//  3. Project status must match handoff_project_status
//  4. If required_checks are configured, all must be in passed_checks
func EvaluateHandoff(input HandoffInput) HandoffResult {
	if input.HandoffProjectStatus == "" {
		return HandoffResult{IsHandoff: false, Reason: "handoff_status not configured"}
	}

	if !input.HasPR {
		return HandoffResult{IsHandoff: false, Reason: "no PR linked"}
	}

	if !strings.EqualFold(input.CurrentProjectStatus, input.HandoffProjectStatus) {
		return HandoffResult{IsHandoff: false, Reason: "status not at handoff value"}
	}

	// Check required CI checks
	if len(input.RequiredChecks) > 0 {
		passed := make(map[string]bool, len(input.PassedChecks))
		for _, c := range input.PassedChecks {
			passed[c] = true
		}
		for _, req := range input.RequiredChecks {
			if !passed[req] {
				return HandoffResult{IsHandoff: false, Reason: "required check not passed: " + req}
			}
		}
	}

	return HandoffResult{IsHandoff: true, Reason: "PR + status + checks met"}
}

// performHandoff pushes the branch, creates a PR, comments on the issue,
// updates project status, and transitions the item to handed_off state.
func (e *Engine) performHandoff(itemID string, item domain.WorkItem, entry *RunningEntry) {
	// Verify item is still in completed state (may have been cancelled/stalled concurrently)
	if current := e.state.ItemState(itemID); current != domain.StateCompleted {
		e.logger.Warn("handoff skipped — item no longer in completed state",
			"item", item.IssueIdentifier, "current_state", current)
		return
	}

	ctx := context.Background()

	if e.codeHost != nil && item.Repository != nil {
		baseBranch := item.Repository.DefaultBranch
		if baseBranch == "" {
			baseBranch = "main"
		}
		branchName := ""
		if entry != nil {
			branchName = entry.BranchName
		}
		if branchName == "" {
			branchName = fmt.Sprintf("%s%s_%s_%d",
				e.cfg.Git.BranchPrefix,
				item.Repository.Owner,
				item.Repository.Name,
				safeIssueNum(item.IssueNumber))
		}

		// Push branch to remote before creating PR
		if e.wsMgr != nil && entry != nil && entry.WorkspacePath != "" {
			pushRemote := e.cfg.Git.PushRemote
			if pushRemote == "" {
				pushRemote = "origin"
			}
			if err := e.wsMgr.PushBranch(entry.WorkspacePath, pushRemote, branchName); err != nil {
				e.logger.Error("branch push failed", "item", item.IssueIdentifier, "error", err)
				_, _ = e.transition(itemID, domain.EventError, nil)
				return
			}
		}

		prResult, err := e.codeHost.UpsertPR(ctx, codehost.PRParams{
			Owner:      item.Repository.Owner,
			Repo:       item.Repository.Name,
			Title:      fmt.Sprintf("[Symphony] %s", item.Title),
			Body:       fmt.Sprintf("Automated PR for %s\n\nGenerated by Symphony.", item.IssueIdentifier),
			HeadBranch: branchName,
			BaseBranch: baseBranch,
			Draft:      e.cfg.PullRequest.DraftByDefault,
		})
		if err != nil {
			e.logger.Error("PR creation failed", "item", item.IssueIdentifier, "error", err)
			_, _ = e.transition(itemID, domain.EventError, nil)
			return
		}

		e.logger.Info("PR created", "item", item.IssueIdentifier, "pr", prResult.URL)

		// Comment on issue
		if e.cfg.PullRequest.CommentOnIssue && item.IssueNumber != nil {
			body := fmt.Sprintf("Symphony created PR #%d: %s", prResult.Number, prResult.URL)
			_, _ = e.codeHost.CommentOnItem(ctx, codehost.ItemRef{
				Owner:  item.Repository.Owner,
				Repo:   item.Repository.Name,
				Number: *item.IssueNumber,
			}, body)
		}

		// Update project status to handoff value
		if e.cfg.PullRequest.HandoffStatus != "" {
			meta, err := e.codeHost.FetchProjectMeta(ctx, codehost.ProjectMetaParams{
				Owner:         e.cfg.Tracker.Owner,
				ProjectNumber: e.cfg.Tracker.ProjectNumber,
				Scope:         e.cfg.Tracker.ProjectScope,
				FieldName:     e.cfg.Tracker.StatusFieldName,
			})
			if err == nil {
				if optionID, ok := meta.Options[e.cfg.PullRequest.HandoffStatus]; ok {
					_ = e.codeHost.UpdateProjectStatus(ctx, codehost.StatusUpdateParams{
						ProjectID: meta.ProjectID,
						ItemID:    item.ProjectItemID,
						FieldID:   meta.FieldID,
						OptionID:  optionID,
					})
				}
			}
		}
	}

	if _, err := e.transition(itemID, domain.EventPRCreated, nil); err != nil {
		e.logger.Error("handoff transition failed", "item", item.IssueIdentifier, "error", err)
		return
	}
	e.state.HandedOff[itemID] = true
	e.state.HandoffTotal++
	e.state.Totals.Writebacks++

	// Persist handoff immediately
	if e.store != nil {
		_ = e.store.SaveHandoff(itemID)
	}

	e.logger.Info("handoff complete", "item", item.IssueIdentifier)
}

func safeIssueNum(n *int) int {
	if n == nil {
		return 0
	}
	return *n
}
